SELECT CARGO FROM EMP
WHERE EMP.NOMBRE = "Joe"
OR (
  NOT ( EMP.CARGO = " Programador ")
  AND ( EMP.CARGO = " Programador " OR EMP.CARGO = " Analista ")
  AND NOT ( EMP.CARGO = " Analista ") 
)

SELECT CARGO FROM EMP
WHERE EMP.NOMBRE = "Joe"
OR (
  NOT P AND ( P OR Q ) AND NOT Q
)

NOT P AND ( P OR Q ) AND NOT Q

¬P AND (P OR Q) AND ¬Q

(¬P AND P) OR (¬P AND Q) AND ¬Q

FALSE OR (¬P AND Q) AND ¬Q

FALSE OR FALSE

FALSE



SELECT COD, SALARIO FROM E1.EMP1 ORDER BY SALARIO
UNION ALL 
SELECT COD, SALARIO FROM E2.EMP2 ORDER BY SALARIO
UNION ALL
SELECT COD, SALARIO FROM E3.EMP3 ORDER BY SALARIO
