version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: remote_user
      POSTGRES_PASSWORD: remote_password
      POSTGRES_DB: remote_db
    ports:
      - "5433:5432"
