version: '3.8'

services:
  postgres1:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    networks:
      - postgres-network

  postgres2:
    image: postgres:latest
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    networks:
      - postgres-network

  postgres3:
    image: postgres:latest
    container_name: postgres3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: db3
    ports:
      - "5435:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
